### ISSUE TITLE
[ CheckMK ] Plugin error if only one channel exists in Mirth Connect

### ISSUE THREAD

**Issue by arevi77** [Kleinrotti/checkmk_mirth#1]
Hello, 
First thanks for your work. 
I get therefore an error using it on Mirth Connect v4.0.0 : 

Traceback (most recent call last):
  File "/opt/omd/sites/openeyes/local/share/check_mk/agents/special/./agent_mirth", line 448, in <module>
    main(args)
  File "/opt/omd/sites/openeyes/local/share/check_mk/agents/special/./agent_mirth", line 413, in main
    channels = process_channels(request_channels())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/omd/sites/openeyes/local/share/check_mk/agents/special/./agent_mirth", line 338, in process_channels
    statistics = request_channel_statistics(c['string'][0])
                                            ~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

Any idea is welcome - Thanks a lot
Best regards
HC

**Comment by Kleinrotti** [comment]
I could reproduce that issue. This happens if only one channel is present in Mirth Connect.
The API response from Mirth Connect changes from this then:
```json
{
  "map": {
    "entry": [
      {
        "string": [
          "c63eb83f-dea8-4539-823a-15a05e6ee872",
          "test1"
        ]
      },
      {
        "string": [
          "c6838b2f-0d38-47c2-aeb2-68c7915bea49",
          "testett"
        ]
      }
    ]
  }
}
```
to this:
```json
{
  "map": {
    "entry": {
      "string": [
        "c63eb83f-dea8-4539-823a-15a05e6ee872",
        "test1"
      ]
    }
  }
}
```

The problem is that "entry" is no longer an array and the parsing fails then. I will work on a fix for that.
If you want a quick work around, just create a new empty channel in Mirth Connect. You don't have to deploy it.

**Comment by arevi77** [comment]
Hello 
Thanks for your feedback. I confirm it's ok with at least 2 channels o).
In any case, we have dozens and dozens of channels in test and production.
Next challenge for us is to upgrade mirth (currently 3.5.1 ... sadness and trouble ahead) ...  
Thanks for your support

**Comment by Kleinrotti** [comment]
Fixed: https://github.com/Kleinrotti/checkmk_mirth/commit/4ce390ad8ad30230ab9fe02efcb23dfcce96b36d
